#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap           0
bspc config left_padding         0
bspc config right_padding        0
bspc config bottom_padding       0
bspc config border_width         1
bspc config top_padding          0


# Hover focus
bspc config focus_follows_pointer true


#  This helps to  when the window in fullscreen the polybar automatically hide
bspc config manage_state false

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Autostart
feh --bg-fill "$HOME/Pictures/wallpapers/Debian.jpg" &
~/.fehbg &
picom &
~/.config/polybar/launch.sh &


#------------ Thunar File Manager Dialog Box Size ----------------------------------------
bspc rule -a Xdg-desktop-portal-gtk state=floating rectangle=1100x1030+0+50 center=off
# For 1366x768 resolution, you can use the following line instead:
#bspc rule -a Xdg-desktop-portal-gtk state=floating rectangle=840x760+0+0 center=off

#------------------------------------------------------------------------------------------