#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Create workspaces
#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10

# Remove default desktop
bspc desktop Desktop -r 2>/dev/null

# ----------------------------------------------------
# BSPWM Settings
# ----------------------------------------------------
bspc config border_width         1
#bspc config top_padding          28
bspc config right_padding        0
bspc config left_padding         0
bspc config bottom_padding       0
bspc config window_gap           0

bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0


# Focus
bspc config focus_follows_pointer true
bspc config split_ratio          0.52

# Monocle
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# ----------------------------------------------------
# Window Rules
# ----------------------------------------------------

# Dialog windows
#bspc rule -a "*" type=dialog state=floating center=on

# Portal dialogs
bspc rule -a Xdg-desktop-portal-gtk state=floating rectangle=840x760+0+0 center=off


# ----------------------------------------------------
# Autostart
# ----------------------------------------------------

$HOME/.config/polybar/launch.sh &

sleep 1

~/.fehbg &
picom &